apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-test
  template:
    metadata:
      labels:
        app: redis-test
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: redis-test
          image: "ghcr.io/jimmybjorklund/redis-test:latest"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /usr/src/app/config
              name: conf
              readOnly: true
          ports:
            - name: "http"
              containerPort: 4000
              protocol: TCP
      volumes:
        - name: "conf"
          projected:
            sources:
            - secret:
                name: "redis-test.conf"
